# CPSO 搜索配置：postalCode 支持多个，按顺序依次搜索并写入数据库
postal_codes:
  # L6T
  - "L6T 0"
  - "L6T 1"
  - "L6T 2"
  - "L6T 3"
  - "L6T 4"
  - "L6T 5"
  - "L6T 6"
  - "L6T 7"
  - "L6T 8"
  - "L6T 9"
  

  # L6X
  - "L6X 0"
  - "L6X 1"
  - "L6X 2"
  - "L6X 3"
  - "L6X 4"
  - "L6X 5"
  - "L6X 6"
  - "L6X 7"
  - "L6X 8"
  - "L6X 9"

  # L6S
  - "L6S 1"
  - "L6S 2"
  - "L6S 3"
  - "L6S 4"
  - "L6S 5"
  - "L6S 6"
  - "L6S 7"
  - "L6S 8"
  - "L6S 9"

  # L6R
  - "L6R 0"
  - "L6R 1"
  - "L6R 2"
  - "L6R 3A"
  - "L6R 3B"
  - "L6R 3C"
  - "L6R 3D"
  - "L6R 3E"
  - "L6R 3F"
  - "L6R 3G"
  - "L6R 3H"
  - "L6R 3J0"
  - "L6R 3J1"
  - "L6R 3J2"
  - "L6R 3J3"
  - "L6R 3J4"
  - "L6R 3J5"
  - "L6R 3J6"
  - "L6R 3J7"
  - "L6R 3J8"
  - "L6R 3J9"
  - "L6R 3K"
  - "L6R 3L"
  - "L6R 3M"
  - "L6R 3N"
  - "L6R 3P"
  - "L6R 3R"
  - "L6R 3S"
  - "L6R 3T"
  - "L6R 3V"
  - "L6R 3W"
  - "L6R 3X"
  - "L6R 3Y"

  # L6W
  - "L6W 0"
  - "L6W 1"
  - "L6W 2A"
  - "L6W 2B"
  - "L6W 2C"
  - "L6W 2D"
  - "L6W 2E"
  - "L6W 2F"
  - "L6W 2G"
  - "L6W 2H"
  - "L6W 2J"
  - "L6W 2K"
  - "L6W 2L"
  - "L6W 2M"
  - "L6W 2N"
  - "L6W 2P"
  - "L6W 2Q"
  - "L6W 2R"
  - "L6W 2S"
  - "L6W 2T"
  - "L6W 2V"
  - "L6W 2W"
  - "L6W 2X"
  - "L6W 2Y"
  - "L6W 2Z0"
  - "L6W 2Z1"
  - "L6W 2Z2"
  - "L6W 2Z3"
  - "L6W 2Z4"
  - "L6W 2Z5"
  - "L6W 2Z6"
  - "L6W 2Z7"
  - "L6W 2Z8"
  - "L6W 2Z9"
  - "L6W 4"
  - "L6W 5"
  - "L6W 6"
  - "L6W 7"
  - "L6W 8"
  - "L6W 9"

  # L6P
  - "L6P 0"
  - "L6P 1"
  - "L6P 2"
  - "L6P 3"
  - "L6P 4"
  - "L6P 5"
  - "L6P 6"
  - "L6P 7"
  - "L6P 8"
  - "L6P 9"

  # L6Y
  - "L6Y 0"
  - "L6Y 1"
  - "L6Y 2"
  - "L6Y 3"
  - "L6Y 4"
  - "L6Y 5"
  - "L6Y 6"
  - "L6Y 7"
  - "L6Y 8"
  - "L6Y 9"

  # L7A
  - "L7A 0"
  - "L7A 1"
  - "L7A 2"
  - "L7A 3"
  - "L7A 4"
  - "L7A 5"
  - "L7A 6"
  - "L7A 7"
  - "L7A 8"
  - "L7A 9"

# 以下为 API 固定参数（可选覆盖）
doctor_type: "Any"
languages: "ENGLISH"
include_inactive: true
